### PR TITLE
Add check for duplicate field names

### PR DESCRIPTION
**Pull request by lalo**
Fix for issue #123 

Example bond file

```
namespace fieldIdWrapping;

struct SameFieldIds
{
    0: int32 FieldWithId0;
    2: string FieldWithId0;
}
```

Error displayed:

```
Error parsing test.bond: "test.bond" (line 7, column 2):
unexpected end of input
Duplicate definition of the field with ordinal 2 and name "FieldWithId0"
```

### CODE REVIEW

**Comment by lalo** [comment]
Had to close to fix issue with line endings

**Comment by lalo** [comment]
Apparently there are tests that have duplicate field names. I should update the tests after making sure that this is an appropriate fix.

**Comment by chwarr** [comment]
Yes, changing `m_enum2` to something else is the right fix. You might have to regenerate the golden master test and include  as well. After building, something like `dist\build\gbc-test\gbc-test --accept` from the `compiler` directory should do it.

**Comment by sapek** [comment]
Given that this is function to find duplicate *fields* calling it `whichField` would be confusing imo.

**Comment by chwarr** [comment]
extractor? selector?

Maybe just combine it into the predicate?
________________________________

**Comment by lalo** [comment]
maybe rename to accessor?

**Pull request closed without merging**
