### PR TITLE
Reference variable, which would otherwise only be referenced in an assert()

### PR DESCRIPTION
**Pull request by jdubrule**
Fix small compile error triggered in VS2015, update 3, in non-debug flavors.

### CODE REVIEW

**Comment by chwarr** [comment]
LGTM. I'll merge this after CI builds finish.

A more robust fix is to not use `assert()` for these sort of things. As currently written, the tests don't test much when `assert()` is disabled, so retail test runs do very little.

**Comment by jdubrule** [comment]
Yeah; seemed too easy not to submit :-)

-jeff

**Comment by chwarr** [comment]
Issue #284 is about the same root problem.

**Comment by chwarr** [comment]
I just pushed a branch (https://github.com/Microsoft/bond/tree/chwarr/comm-unref) with this fix and one for the problems in #284. After those CI builds pass, I'll merge it in, which will close this PR.

**Pull request closed without merging**
