### PR TITLE
Remove support for .NET 4.0

### PR DESCRIPTION
**Pull request by chadwalters**
Also, remove the reflection shim designed to cover over API differences in .NET 4.0 and 4.5.

### CODE REVIEW

**Comment by chwarr** [comment]
The .NET Core build failed. Our AppVeyor config doesn't actually dump the errors to the log correctly, so you'll need to re-run that part of the build locally to get the errors. Sorry about the inconvenience. (This will get better when we can migrate to MSBuild 15 for all our build stuff instead of having this split build system.)

**Comment by chwarr** [comment]
The nuproj files also need to be updated to remove the references to net40, but aside from that, LGTM.

**Comment by chadwalters** [comment]
.nuspec files updated. Also removed cruft in Config.cmake and all usages of the NET45 constant.

**Comment by chwarr** [comment]
Merge into master in commit 31211e10.

**Pull request closed without merging**
