### PR TITLE
[C++] Various small improvements and fixes

### PR DESCRIPTION
**Pull request by chadwalters**
[C++] Move is_bonded<T> to traits.h
[gbc] Add test for C++ enum header option
[gbc] Include stdint.h in C++ enum header
[C++] Use std::integral_constant<> to avoid some odd compiler bugs in VC12

### CODE REVIEW

**Comment by glenfe** [comment]
The use of `std::integral_constant` forfeits C++98/C++03 compatibility but the README.md still indicates those are supported; `boost::integral_constant` is available if you want to preserve it.

**Comment by chadwalters** [comment]
I tried this with boost::integral_constant and go a warning from VC12. We're ready to move forward to C++11 -- or at least the subset supported by VC12 -- in any case. I update the README to reflect this.

**Comment by chadwalters** [comment]
The AppVeyor failure is the standard timeout issue. This change should be OK to go into master now ("Rebase and Merge", don't squash).

**Comment by chwarr** [comment]
LGTM. Command line merge in progress.

**Comment by chwarr** [comment]
Rebase merged--with a changelog and README update--in commit fd9a1866.

**Pull request closed without merging**
