### PR TITLE
[c++ c#] Remove Bond Comm

### PR DESCRIPTION
**Pull request by chwarr**
Closes https://github.com/Microsoft/bond/issues/824

### CODE REVIEW

**Comment by chwarr** [comment]
Can you point out where in the docs we forgot to remove things? I tried to find them all, but I'm not at all surprised that my grep missed some.

**Comment by chwarr** [comment]
Something went wrong during a rebase and a bunch of comm stuff has been resurrected. Let me clean that up.

**Comment by ara-ayvazyan** [comment]
>     , verifyCppCommCodegen

Remove?

---
Refers to: compiler/tests/Tests/Codegen.hs:10 in 0e6f6b7. [](commit_id = 0e6f6b72057a290b4a7cda83a44b2d82f41e7eb2, deletion_comment = False)

**Comment by ara-ayvazyan** [comment]
>     , verifyCsCommCodegen

Remove?

---
Refers to: compiler/tests/Tests/Codegen.hs:15 in 0e6f6b7. [](commit_id = 0e6f6b72057a290b4a7cda83a44b2d82f41e7eb2, deletion_comment = False)

**Comment by ara-ayvazyan** [comment]
>     ${comm-flag} ${grpc-flag}

Remove?

---
Refers to: cpp/CMakeLists.txt:14 in 0e6f6b7. [](commit_id = 0e6f6b72057a290b4a7cda83a44b2d82f41e7eb2, deletion_comment = False)

**Comment by ara-ayvazyan** [comment]
>     ${comm-flag} ${grpc-flag}

Remove?

---
Refers to: cpp/CMakeLists.txt:26 in 0e6f6b7. [](commit_id = 0e6f6b72057a290b4a7cda83a44b2d82f41e7eb2, deletion_comment = False)

**Comment by chwarr** [comment]
@ara-ayvazyan, @tstein: I think I fixed up the left over Comm bits from the bad rebase. Please review anew.

**Comment by chwarr** [comment]
Looks like AppVeyor isn't running because I touched .travis.yml...

**Comment by tstein** [comment]
I was referring to the docs in `doc/src/`, where there several marksdown with comm in their filenames and probably some references in others. I think they've escaped this change so far.

**Comment by chwarr** [comment]
Deleted the comm Markdown files. Thanks!

**Pull request merged**
