### PR TITLE
[c#] Swap in a custom list for SynchronizedCollection

### PR DESCRIPTION
**Pull request by chwarr**
SynchronizedCollection is not present in .NET Standard 1.6, among others. It
was only being used to demonstrate how collection type aliasing works, so it
has been replaced with SomeCustomList<T> which just wraps List<T> to
demonstrate how this would work.

### CODE REVIEW

**Comment by chwarr** [comment]
Rebased atop latest Mono fixes. Re-running CI.

**Comment by chadwalters** [comment]
The CI failures seem to be real failures related to this change.

**Comment by chwarr** [comment]
Yup. I broke something somewhere during the rebase. Looking...

**Comment by chwarr** [comment]
Fixed it for .NET. Letting CI run to check Mono.

Also opened ["Custom collections need to implement ICollection and not just ICollection<T>"][i254] to fix a discrepancy between the documentation and the implementation around custom containers.

[i254]: https://github.com/Microsoft/bond/issues/254

**Comment by chwarr** [comment]
AppVeyor failure is a C++ timeout. PR #256 should help with these. Going ahead with the merge.

**Pull request closed without merging**
