### PR TITLE
Explicit dependency for enumerations.csproj

### PR DESCRIPTION
**Pull request by lalo**

### CODE REVIEW

**Comment by lalo** [comment]
Took a stab at #1072 but couldn't make it work. Must be misinterpreting the error message, also I wonder how it regressed?

**Comment by chwarr** [comment]
Thanks for trying. I suspect a newer version of the .NET SDK was installed that resolves our under-specified dependencies differently. I _think_ the fix is to use `<ProjectReference>` everywhere instead of `<HintPath>$(BOND_BINARY_PATH)\net45\Bond.Attributes.dll</HintPath>`.

This isn't something I'll have time to do in the next few months at least...

**Comment by chwarr** [comment]
I looked at the error messages for your build. I think enumerations.csproj is fixed now. It looks like there are other projects that are missing dependencies too. I still think that `<ProjectReference>` is the robust way forward, but SLN changes to get this building again in the meantime are fine by me.

**Comment by lalo** [comment]
Yea, that makes sense. This might be simple with a vim macro.

**Pull request closed without merging**
